spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:${MYSQL_LOCAL_PORT}/${DB_NAME}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}

file:
  access-url-base: http://localhost:8080/files/
  storage-path: C:/sp_board/files/
  directories:
    member: member
    board: board