spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:${MYSQL_LOCAL_PORT}/${DB_NAME}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: localhost
      port: ${REDIS_LOCAL_PORT}  # 환경변수 없으면 기본 6379
      database: 0

file:
  access-url-base: http://localhost:8080/files/
  storage-path: C:/sp_board/files/
  directories:
    member: member
    board: board